# Form implementation generated from reading ui file '.\UI Designs\Customer Add UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerAdd(object):
    def setupUi(self, CustomerAdd):
        CustomerAdd.setObjectName("CustomerAdd")
        CustomerAdd.resize(327, 323)
        CustomerAdd.setStyleSheet("background:rgb(255, 255, 255)")
        self.labelCustomerName = QtWidgets.QLabel(parent=CustomerAdd)
        self.labelCustomerName.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCustomerName.setFont(font)
        self.labelCustomerName.setObjectName("labelCustomerName")
        self.textEditCustomerName = QtWidgets.QTextEdit(parent=CustomerAdd)
        self.textEditCustomerName.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.textEditCustomerName.setObjectName("textEditCustomerName")
        self.textEditCustomerPhoneNo = QtWidgets.QTextEdit(parent=CustomerAdd)
        self.textEditCustomerPhoneNo.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.textEditCustomerPhoneNo.setObjectName("textEditCustomerPhoneNo")
        self.labelCustomerPhoneNo = QtWidgets.QLabel(parent=CustomerAdd)
        self.labelCustomerPhoneNo.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCustomerPhoneNo.setFont(font)
        self.labelCustomerPhoneNo.setObjectName("labelCustomerPhoneNo")
        self.textEditCustomerEmail = QtWidgets.QTextEdit(parent=CustomerAdd)
        self.textEditCustomerEmail.setGeometry(QtCore.QRect(10, 150, 181, 31))
        self.textEditCustomerEmail.setObjectName("textEditCustomerEmail")
        self.labelCustomerEmail = QtWidgets.QLabel(parent=CustomerAdd)
        self.labelCustomerEmail.setGeometry(QtCore.QRect(10, 130, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCustomerEmail.setFont(font)
        self.labelCustomerEmail.setObjectName("labelCustomerEmail")
        self.textEditCustomerAddress = QtWidgets.QTextEdit(parent=CustomerAdd)
        self.textEditCustomerAddress.setGeometry(QtCore.QRect(10, 210, 181, 31))
        self.textEditCustomerAddress.setObjectName("textEditCustomerAddress")
        self.labelCustomerAddress = QtWidgets.QLabel(parent=CustomerAdd)
        self.labelCustomerAddress.setGeometry(QtCore.QRect(10, 190, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCustomerAddress.setFont(font)
        self.labelCustomerAddress.setObjectName("labelCustomerAddress")
        self.DeleteData = QtWidgets.QPushButton(parent=CustomerAdd)
        self.DeleteData.setGeometry(QtCore.QRect(220, 20, 81, 24))
        self.DeleteData.setObjectName("DeleteData")
        self.AudioInputPushButton = QtWidgets.QPushButton(parent=CustomerAdd)
        self.AudioInputPushButton.setGeometry(QtCore.QRect(220, 120, 81, 31))
        self.AudioInputPushButton.setObjectName("AudioInputPushButton")
        self.SaveData = QtWidgets.QPushButton(parent=CustomerAdd)
        self.SaveData.setGeometry(QtCore.QRect(220, 80, 81, 21))
        self.SaveData.setObjectName("SaveData")
        self.labelCustomerGSTno = QtWidgets.QLabel(parent=CustomerAdd)
        self.labelCustomerGSTno.setGeometry(QtCore.QRect(10, 250, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCustomerGSTno.setFont(font)
        self.labelCustomerGSTno.setObjectName("labelCustomerGSTno")
        self.textEditGSTno = QtWidgets.QTextEdit(parent=CustomerAdd)
        self.textEditGSTno.setGeometry(QtCore.QRect(10, 270, 291, 31))
        self.textEditGSTno.setObjectName("textEditGSTno")

        self.retranslateUi(CustomerAdd)
        QtCore.QMetaObject.connectSlotsByName(CustomerAdd)

    def retranslateUi(self, CustomerAdd):
        _translate = QtCore.QCoreApplication.translate
        CustomerAdd.setWindowTitle(_translate("CustomerAdd", "Form"))
        self.labelCustomerName.setText(_translate("CustomerAdd", "Customer Name"))
        self.labelCustomerPhoneNo.setText(_translate("CustomerAdd", "Customer Phone no."))
        self.labelCustomerEmail.setText(_translate("CustomerAdd", "Customer Email"))
        self.labelCustomerAddress.setText(_translate("CustomerAdd", "Customer Address"))
        self.DeleteData.setText(_translate("CustomerAdd", "Delete"))
        self.AudioInputPushButton.setText(_translate("CustomerAdd", "Audio Input"))
        self.SaveData.setText(_translate("CustomerAdd", "Save"))
        self.labelCustomerGSTno.setText(_translate("CustomerAdd", "Customer GST no."))
