# Form implementation generated from reading ui file '.\UI Designs\Delete Confirmation UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteConfirmation(object):
    def setupUi(self, DeleteConfirmation):
        DeleteConfirmation.setObjectName("DeleteConfirmation")
        DeleteConfirmation.resize(400, 121)
        DeleteConfirmation.setStyleSheet("background:rgb(255, 255, 255)")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DeleteConfirmation)
        self.buttonBox.setGeometry(QtCore.QRect(40, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=DeleteConfirmation)
        self.label.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(DeleteConfirmation)
        self.buttonBox.accepted.connect(DeleteConfirmation.accept) # type: ignore
        self.buttonBox.rejected.connect(DeleteConfirmation.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteConfirmation)

    def retranslateUi(self, DeleteConfirmation):
        _translate = QtCore.QCoreApplication.translate
        DeleteConfirmation.setWindowTitle(_translate("DeleteConfirmation", "Dialog"))
        self.label.setText(_translate("DeleteConfirmation", "Do you really want to Delete this?"))
