from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from Python_UI_Scripts.raw_slip_entry import Ui_RawSlip
import sys

class Ui_WelcomeWindow(object):

    def openRawSlipEntry(self):
        self.RSwindow = QMainWindow()

        self.RSui = Ui_RawSlip()
        self.RSui.setupUi(self.RSwindow)

        self.RSwindow.show()

    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(801, 602)
        WelcomeWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.label.setStyleSheet("background:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.289773 rgba(184, 206, 224, 255), stop:0.932203 rgba(21, 76, 121, 255))")
        self.label.setObjectName("label")
        WelcomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WelcomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        self.menuAI_Baniya = QtWidgets.QMenu(parent=self.menubar)
        self.menuAI_Baniya.setObjectName("menuAI_Baniya")
        self.menuData_Entry = QtWidgets.QMenu(parent=self.menubar)
        self.menuData_Entry.setObjectName("menuData_Entry")
        self.menuData_Analysis_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menuData_Analysis_2.setObjectName("menuData_Analysis_2")
        self.menuInventory_Stock = QtWidgets.QMenu(parent=self.menubar)
        self.menuInventory_Stock.setObjectName("menuInventory_Stock")
        self.menuData_Storage = QtWidgets.QMenu(parent=self.menubar)
        self.menuData_Storage.setObjectName("menuData_Storage")
        self.menuWorkforce = QtWidgets.QMenu(parent=self.menubar)
        self.menuWorkforce.setObjectName("menuWorkforce")
        WelcomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WelcomeWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        WelcomeWindow.setStatusBar(self.statusbar)
        self.actionData_Entry = QtGui.QAction(parent=WelcomeWindow)
        self.actionData_Entry.setObjectName("actionData_Entry")
        self.actionData_Entry.triggered.connect(slot=lambda:self.openRawSlipEntry())
        self.actionInventory_Stock = QtGui.QAction(parent=WelcomeWindow)
        self.actionInventory_Stock.setObjectName("actionInventory_Stock")
        self.actionRaw_Firm = QtGui.QAction(parent=WelcomeWindow)
        self.actionRaw_Firm.setObjectName("actionRaw_Firm")
        self.actionMain_Firms = QtGui.QAction(parent=WelcomeWindow)
        self.actionMain_Firms.setObjectName("actionMain_Firms")
        self.actionFuture_Prediction = QtGui.QAction(parent=WelcomeWindow)
        self.actionFuture_Prediction.setObjectName("actionFuture_Prediction")
        self.actionCurrent_Stock_Analysis = QtGui.QAction(parent=WelcomeWindow)
        self.actionCurrent_Stock_Analysis.setObjectName("actionCurrent_Stock_Analysis")
        self.actionData_Storage = QtGui.QAction(parent=WelcomeWindow)
        self.actionData_Storage.setObjectName("actionData_Storage")
        self.menubar.addAction(self.menuAI_Baniya.menuAction())
        self.menubar.addAction(self.menuData_Entry.menuAction())
        self.menuData_Entry.addAction(self.actionData_Entry)
        self.menubar.addAction(self.menuData_Analysis_2.menuAction())
        self.menubar.addAction(self.menuInventory_Stock.menuAction())
        self.menubar.addAction(self.menuData_Storage.menuAction())
        self.menubar.addAction(self.menuWorkforce.menuAction())

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "MainWindow"))
        self.label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:700; text-decoration: underline; color:#102246;\">AI Baniya</span></p><p align=\"center\"><span style=\" font-size:11pt; color:#102246;\">Welcomes You</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#102246;\">In your Personal</span></p><p align=\"center\"><span style=\" font-size:22pt; font-weight:700; color:#102246;\">Accounts Management System</span></p></body></html>"))
        self.menuAI_Baniya.setTitle(_translate("WelcomeWindow", "AI Baniya"))
        self.menuData_Entry.setTitle(_translate("WelcomeWindow", "Data Entry"))
        self.menuData_Analysis_2.setTitle(_translate("WelcomeWindow", "Data Analysis"))
        self.menuInventory_Stock.setTitle(_translate("WelcomeWindow", "Inventory/Stock"))
        self.menuData_Storage.setTitle(_translate("WelcomeWindow", "Data Storage"))
        self.menuWorkforce.setTitle(_translate("WelcomeWindow", "Workforce"))
        self.actionData_Entry.setText(_translate("WelcomeWindow", "Data Entry"))
        self.actionInventory_Stock.setText(_translate("WelcomeWindow", "Inventory/Stock"))
        self.actionRaw_Firm.setText(_translate("WelcomeWindow", "Raw Firm"))
        self.actionMain_Firms.setText(_translate("WelcomeWindow", "Main Firms"))
        self.actionFuture_Prediction.setText(_translate("WelcomeWindow", "Future Prediction"))
        self.actionCurrent_Stock_Analysis.setText(_translate("WelcomeWindow", "Current Stock Analysis"))
        self.actionData_Storage.setText(_translate("WelcomeWindow", "Data Storage"))
