# Form implementation generated from reading ui file '.\UI Designs\Existing Item Confirmation UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExistingItemCheck(object):
    def setupUi(self, ExistingItemCheck):
        ExistingItemCheck.setObjectName("ExistingItemCheck")
        ExistingItemCheck.resize(471, 247)
        ExistingItemCheck.setStyleSheet("background:rgb(255, 255, 255)")
        self.buttonBoxItemData = QtWidgets.QDialogButtonBox(parent=ExistingItemCheck)
        self.buttonBoxItemData.setGeometry(QtCore.QRect(120, 210, 341, 32))
        self.buttonBoxItemData.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBoxItemData.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBoxItemData.setObjectName("buttonBoxItemData")
        self.comboBoxItemDetailShow = QtWidgets.QComboBox(parent=ExistingItemCheck)
        self.comboBoxItemDetailShow.setGeometry(QtCore.QRect(0, 60, 471, 91))
        self.comboBoxItemDetailShow.setStyleSheet("background:rgb(255, 255, 255)")
        self.comboBoxItemDetailShow.setObjectName("comboBoxItemDetailShow")
        self.comboBoxItemDetailShow.addItem("")
        self.textBrowserWarning = QtWidgets.QTextBrowser(parent=ExistingItemCheck)
        self.textBrowserWarning.setGeometry(QtCore.QRect(0, 10, 471, 51))
        self.textBrowserWarning.setObjectName("textBrowserWarning")

        self.retranslateUi(ExistingItemCheck)
        self.buttonBoxItemData.accepted.connect(ExistingItemCheck.accept) # type: ignore
        self.buttonBoxItemData.rejected.connect(ExistingItemCheck.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExistingItemCheck)

    def retranslateUi(self, ExistingItemCheck):
        _translate = QtCore.QCoreApplication.translate
        ExistingItemCheck.setWindowTitle(_translate("ExistingItemCheck", "Dialog"))
        self.comboBoxItemDetailShow.setItemText(0, _translate("ExistingItemCheck", "Item Details"))
        self.textBrowserWarning.setHtml(_translate("ExistingItemCheck", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Item already exist in Database please Choose one below and press OK to use it or press Cancel to add new customer.</span></p></body></html>"))
